[theme]
background = "default"
primary = "#e0d0f0"
secondary = "#7a6589"
title = "#ff9e64"
playing = "#c792ea"
playing_selected = "#e0aaff"
playing_bg = "default"
highlight = "#ffcb91"
highlight_bg = "#3b2751"
error = "#ffe0e0"
error_bg = "#a83232"
statusbar = "#1a1028"
statusbar_progress = "#ff9e64"
statusbar_bg = "#c792ea"
cmdline = "#e0d0f0"
cmdline_bg = "default"
search_match = "#ff9e64"
